### ISSUE TITLE
How to rename a shard

### ISSUE THREAD

**Issue by zamith** [crystal-lang/shards#109]
This is more of question than an issue, and maybe there's a better place to ask it but I don't exactly know where, so sorry about that.

What's the best way to rename a shard? Is there a command for it, or a defined set of steps?

**Comment by ysbaddaden** [comment]
Since Shards is decentralized, renaming a shard only requires to change the `name` entry in `shard.yml` and maybe the library entry file. For example renaming `src/foo.cr` to `src/bar.cr` if we rename a `foo` shard to `bar`.

That being said any library that depends on the shard will break, since the dependency can't be found anymore, and it will end up with a naming conflict.

**Comment by zamith** [comment]
Would it possible to solve this the Ruby way, by adding the new shard as a
dependency of the old?

**Comment by ysbaddaden** [comment]
As long as the old one requires the new one specifically with `require` otherwise the files won't be found. We only reference the folders containing shards in CRYSTAL_PATH (eg. `libs`, not every specified folders of each gem (eg. `gems/foo-x.y.z/lib`). Just requiring the new shard is thus not enough.

**Comment by zamith** [comment]
Oh, I see. The main problem here is then a communication problem, where as a maintainer you have to reach all you users and tell them to change to the new shard. There is nothing in shards (the package manager) that can help you with that. Correct?

I think that answers my question, so I'm closing the issue. Thanks.
