### ISSUE TITLE
Clarification on the relationship of shards releases to crystal releases

### ISSUE THREAD

**Issue by RX14** [crystal-lang/shards#155]
I am currently writing a (very WIP) version manager for crystal, and have a question on how I should handle shards versioning in relation to crystal versioning.

Currently with the crystal omnibus, a version of shards is built and distributed alongside crystal, available as `crystal deps`. Similarly on OSX, `shards` is part of the crystal formula for homebrew. Crenv uses [a json file](https://github.com/pine/crystal-build/blob/master/share/crystal-build/shards.json) to select the shards version for a crystal release, which seems a bit of a hack.

Are shards versions considered to be pinned for a specific crystal version (i.e. a version of crystal has a specific shards version it should use), or should the latest version of shards always be used? Obviously compatibility is an issue with the latter approach, but some simple rules (v1 require algo / v2 require algo) should clear that up.

If we decide that a specific version of shards should be used for each release of crystal, I would like to see a new shards release for each crystal version, using the same version numbers (e.g. shards 0.21.2 for crystal 0.21.2). This would make it easy to know which version of shards to install.

**Comment by ysbaddaden** [comment]
Shards and Crystal are released independently. Hopefully the latest Shards should be used.

We only required a synced release once, because the `require` rules changed. I don't think that will happen again.

That being said, until Crystal is 1.0 and thus more stable, a new Shards may be released with a compilation fix when Crystal is released.

Maybe the best approach is to pin the latest compatible version available, or just download a release tarball of Crystal, shipped with Shards already.

**Comment by RX14** [comment]
I think I'll manage shards versions completely independently of crystal versions for now, using the `version` field of shard's `shard.yml` as the crystal version to compile shards with (please keep this up to date!). That should do for forwards compatibility, I'll solve the possibility of installing earlier versions of shards further down the line.

Thanks!
