### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by pta2002** [crystal-lang/shards#157]
I have a suggestion for a new command: `shards run [target] [args]`. This would be the same as executing `shards build [target]` and then running the compiled file with the arguments specified, just shortened to one command. This can be useful for quickly testing out new changes, without needing to run two commands. In fact, crystal already has a `run` command, so maybe use that instead of outputting the file?

**Comment by GloverDonovan** [comment]
`shards run` would be great. Rust has [something similar](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_run.rs) and it helps a lot when you only have to use one command instead of multiple for quick changes.

**Comment by ysbaddaden** [comment]
There may be many targets configured to build. Which one should a run command execute? Do binaries depend on each other? So, shall we build all targets, then run a single one?

Build is a minimalistic tool, and meant to stay this way; I don't want to add any more configuration. I'm not sure we can achieve anything proper for most scenarios without adding configuration.

**Comment by RX14** [comment]
If there's more than one target, you must specify `shards run target`. No dependencies between targets. That's a simple zero-config way to do this.

**Comment by ysbaddaden** [comment]
So `shards run [target]` where `target` can be omitted if only one is configured (no ambiguity) and prints a helpful error message otherwise. That sounds acceptable. Not really my workflow, but I understand it can be.

If someone wants to take a stab at this, with a integration tests, updated man pages, please do.

**Comment by eliasjpr** [comment]
@ysbaddaden this is really helpful and benefits some web projects that happen to need to run scripts on remote servers with limited access and permission.

**Comment by ysbaddaden** [comment]
Well, I'd deploy pre-built binaries, not the source code, avoiding to install crystal/shards on production servers.

**Comment by arnavb** [comment]
Has there been any progress on this? I'd also like to see this command implemented (it makes it much more sane to run Rust projects, from my experience).

**Comment by straight-shoota** [comment]
I don't think so. But it should be rather easy to implement. If you're willing to take a stab at this, go ahead :+1:

**Comment by denolfe** [comment]
Is this being worked on? If not, I'd like to take a stab at it.

**Comment by denolfe** [comment]
Initial implementation here: https://github.com/denolfe/shards/commits/run-command. Any feedback is welcome.

I wrapped the build command because there needed to be some additional logic for checking for a number of targets then handling appropriately. It didn't make sense to me to shove that into `cli.cr`. Tests yet to be added.

**Comment by ysbaddaden** [comment]
Great! Please open a draft pull request so we can talk about this implementation.

**Comment by denolfe** [comment]
PR opened in #298.

One thing that was not discussed at length: Should we allow some sort of default target name that will attempt to be run when `shards run` is executed without a target name? The discussions above indicate that `shards run` should actually error out if more than 1 target is specified in `shard.yml` (this functionality is in the PR). Is this still desired?

**Comment by ysbaddaden** [comment]
Yes. No default, unless there is only 1 target.

**Comment by straight-shoota** [comment]
I'm not sure whether the default behaviour is a good idea. `shards build` defaults to building all. `shards run` defaults to running one, but only if there is one defined seems off.
Maybe it should just print a list of available targets?

**Comment by sam0x17** [comment]
I'm fine with it erroring out or printing the list of targets if there are multiple targets, though my preferred behavior would be to run the first target that is listed in shards.yml.

**Comment by sam0x17** [comment]
So to re-iterate, I'd like to base the default off the ordering of targets in shards.yml unless user specifies a particular target to run

**Comment by sam0x17** [comment]
Also to illustrate the need for this, right now my workaround is doing `crystal run src/*` which is just bad for a number of reasons.

**Comment by straight-shoota** [comment]
Always running the first target if no name specified sounds good. That's consistent behaviour.

**Comment by ysbaddaden** [comment]
The onky consistent behavior is always asking a target, even when only one is present. But *that* would be annoying because we can easily infer the target when there is only one. An ordered list of targets has no meaning (its just a bunch of targets).

Let's go with erroring and see how it goes.

**Comment by straight-shoota** [comment]
When specifying targets, I usually put the main one up front. When I want to execute a target, it's most often this one because it's the most important.

The thing with consistency is: When a Share has only one target, `shards run` works just fine. Assuming another target is added for some kind of auxiliary app, `shards run` breaks. But this change is unavoidable (unless you drop the second target). When always running the first target, `shrds run` keeps working Ben with a second target. You know need to append it after the previous one, but that's totally in control of the author.

An alternative would be to add property to specify the main target. But that adds additional complexity when target order is sufficient.

**Comment by ysbaddaden** [comment]
As I said: the only consistent behavior is to *always* require the target. Shards isn't a build tool after all, it only provides a basic build command and now a run command with no configuration, except for entry points.

**Comment by sam0x17** [comment]
I don’t see why we have to be consistent in this way. There is literally no reason not to default to the first target. If there is an actual concern, we could print “multiple targets detected, running first target (target name)”. Requiring people to type in the name of the target every time largely defeats the purpose of making running a shard a one-line thing that can be done consistently, in a way the shard author can control, and without the user having to investigate the shard.yml file. How does the author control it? By ordering the targets list appropriately, as they probably already do. The benefit of providing this convenience vastly outweighs “consistency”.

We can clearly document this in the shards.yml documentation. `shards run` will run the first target listed in `shards.yml`, or the target specified by `shards run —target [target]`. Simple, easy, actually helpful to the user instead of annoyingly pedantic.

**Comment by sam0x17** [comment]
Also, shards literally is a build tool. We have a `shards build` command, and that can trigger tons of complex makefile operations and various things because we support hooks.

**Comment by sam0x17** [comment]
I would say that shards is in fact a build tool. We have a `shards build` command, and lots of shards have complex makefiles that get triggered by our hooks system.

I also don't think we need to be conservative here. It's not like we are releasing a breaking change to an existing `shards run` syntax. There is no `shards run` syntax. I say default to first target, but always print `"running first target (target name)"`, and allow overriding this with `shards run --target [target]`.

**Comment by sam0x17** [comment]
Oh and to be silly, we could of course run _all_ targets 😜

**Comment by ysbaddaden** [comment]
I lean more and more on always specifying the target to run: consistent, no configuration, no documentation, no repeated boring message (that boils down to: you should always specify the target), no surprises (you know what will happen).

Targets can be ordered for whatever reasons. Personal preference, alphabetical, to follow a specific build order, where the main target is the last one. Always building the first target is just a habit from `make`, it ain't that terrible because `make` has build dependencies (each target depends on others). 

Shards isn't a build tool, and will never support such features. They're out of scope, and Shards already can't even do what's in scope properly (resolve and install libraries).

If typing `shards run complicated_target_name_i_can_never_get_right` is boring (I agree), I encourage you to create a Makefile, so you can just type `make` instead.

**Comment by sam0x17** [comment]
I would concede and say OK let's default to the first one when there is only one, and otherwise error unless a target is specified.

That said, I really don't get what the fear is here. What is the bad side effect we are afraid of causing? Someone has 3 targets, and the "main" one isn't listed first? Not exactly a tragedy.

Running the first target is a perfect example of convention over configuration, and will give users an easier time in general. It might be a convention from Make, but it's a widely recognized convention, and a logical one (i.e. the important thing goes first). If I was doing a code review, and someone listed an ancillary target first, I would probably provide feedback that they should list the primary target first to better follow the principle of least surprise.

As far as shards not being a build tool, I really don't see how that is true. It's perfectly analogous to `cargo` in the Rust community, and no one is going to argue that `cargo` isn't a build tool. If I run it, and makefile stuff can start happening in the background, then it's a build tool. That doesn't mean we need to scope-creep tons of new features in, but we should at least be honest with ourselves.

**Comment by Sija** [comment]
`build` and `run` commands have IMO visibly different semantics - having 1 target seems clear and it's obvious what happens when you run `shards build`, OTOH running `shards run` without an argument is pretty confusing - what actually does it do? does it run just one command, if so - which one - ah, the only one - but is it consistent between the projects? nope. `shards run` would be very much project dependent, unlike for instance `rake` or `npm` which by default will run only `test` task (if found).

**Comment by sam0x17** [comment]
@Sija npm does that because in the nodejs world, `node .` will typically actually work, whereas there isn't a good equivalent with crystal. Yes we have `crystal run` but it (unlike node / npm) ignores `shards.yml`. In the node case, it will actually look at package.json to figure out what file to run. You could say that behavior is very broken, and a better behavior would be that `npm` will run the entry file by default.

I'll be honest, I find it quite annoying that we even have multiple targets. I see it as a necessary evil. I think of a shard as either an app or a library. If it's an app, it makes sense to run it, and I shouldn't have to know intimate things about the app to know how to run it. I should be able to just `shards run` and magic happens.

**Comment by straight-shoota** [comment]
There is now an implementation proposed in https://github.com/crystal-lang/shards/pull/546

For getting that finialized we need a definitive answer to how the `target` argument, and especially its absence should work.

We can consider these cases:

* When the `target` argument is present, that target should be built and run.
* When there are no targets in `shard.yml`, that's clearly an error.
* Unclear is what happens when the `target` argument is missing, especially when there are multiple targets in `shard.yml`.
  * a) Require the `target` argument when there are multiple targets. Missing argument could be an error, or more user friendly, print a list of available targets.
  * b) Default to the first target by order of definition.
  	 An alteration on that could use some some other means to determine the default target, for example by target key or with a `default: true` property. I don't see a reasonable benefit over simple definition order, though.

When there is only a single target in `shard.yml`, it should be reasonable to run that one. This would be consistent with option b). Alternatively, it could be an error or show a list of available targets. This would be a bit silly when there is only one target, but this would be consistent with option a).
Because of these consistency considerations I believe the case that there is only a single target in `shard.yml` shouldn't be in any way special. It should rather derive from the behaviour with multiple targets.
For example, it would be odd if `shards run` prints a list of targets only if there is over one. You would need to know how many targets there are in order to figure out what behaviour to expect.

As mentioned before, I'm in favour of option b). I believe it is the most expectable behaviour.

**Comment by beta-ziliani** [comment]
I don't think we need to have it all figured out at once. I would go first with: if there is one, run it, if there are many, error and (optionally) list them. Anything else can be coded afterwards.
