### ISSUE TITLE
Invalid Int32 when specifying a commit

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/shards#162]
This
```
dotenv:
  github: gdotdesign/cr-dotenv
  commit: 341678090110cdb5436f75cc796c785ed392c4be
```
fails with
```
Updating https://github.com/gdotdesign/cr-dotenv.git
Invalid Int32: 341678090110 (ArgumentError)
```
I suppose this is a bug.

Even wrapping in double quotes (`"341678090110cdb5436f75cc796c785ed392c4be"`) raises the same error.

**Comment by ysbaddaden** [comment]
I don't understand why specifying a `commit` hash ends up calling `NaturalSort` on this hash. That shouldn't happen, I guess.

**Comment by ysbaddaden** [comment]
The problem is `GitResolver#available_versions` that injects the specified Git refs as an "available version" (it even defaults to `HEAD`). I guess we should just resolve the `version_at(refs)` but make sure later on to override the resolved version with the specified ref (when installing & locking).
