### ISSUE TITLE
Add man page

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#187]
suggested in crystal-lang/crystal-book#174

**Comment by ysbaddaden** [comment]
There are already. They may not be installed by distributiond, but there are.

**Comment by RX14** [comment]
Perhaps it should be moved out of the `src` folder.

**Comment by straight-shoota** [comment]
That's why I didn't see it.

But the issue is not just about having a man page in the project repository, but to make it available to people who are using `shards`. How do we get it in the distribution packages?

**Comment by RX14** [comment]
@straight-shoota make it obvious or tell the distributors about it. Or provide a `make install`.

**Comment by GloverDonovan** [comment]
I believe that the package maintainer for Arch would've included the man pages if he knew they were there, since he already included them for the [`crystal`](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/crystal) package. I also did not assume that the man pages would be in `src`.

I have created a pull request to use a top-level `man` directory, just like Crystal itself. This should make it easier for package maintainers to know that these man pages exist.
