### ISSUE TITLE
Support complex expressions

### ISSUE THREAD

**Issue by j8r** [crystal-lang/shards#196]
Support complex expressions, like [npm's semver implementation](https://www.npmjs.com/package/semver) like "or" `||` and hyphen ranges.

I've implemented most of them with the npm's syntax in [semantic_compare](https://github.com/j8r/semantic_compare) (caret ranges `^` instead of `~>` and no space between the operator and version number)

**Comment by j8r** [comment]
To add some context: the Ruby inspired gem syntax can be kept, but the use case is when we support LTS versions of a library - we need an expression like `~> 1.2.0 || ~> 2.4.0`

**Comment by ysbaddaden** [comment]
To be honest I never needed any of these.

1. forcing no space between operator and version makes no sense to me (arbitrary parsing rule).

2. I don't understand the `||` rule: multiple versions should restrict versions, not expand them arbitrarily. Furthermore Crystal ain't even aiming for a stable release, libraries even less, so long-term-support for libraries seems soooo far away.

3. The `^` constraint always confuses me, especially since one should *never* expect a minor version to never break (it will). I believe the `~>` requirement is far more safe, along with an `outdated` command to easily search for outdated dependencies.

4. Shards doesn't require semver. It happens to support it, but doesn't enforce it in any way.

All in all, I believe an `outdated` command and supporting pre-release versions (see #184) would be more useful than supporting `^` or `||` for the time being.

**Comment by j8r** [comment]
I never said to port caret or tilde ranges, but having a way to have the "or" operator `||` and hyphen ranges. This way we can restrict versions between one to another, that are tested to work properly. A program works for versions after `1.2.9` until `1.4.7` for example, that is untested.

**Comment by ysbaddaden** [comment]
Superseded by #261
