### ISSUE TITLE
Rename dependencies to requirements

### ISSUE THREAD

**Issue by trans** [crystal-lang/shards#213]
Something that always irked me about gemspecs is the backward use of the words "dependency" and "requirement". In Ruby, as in Crystal, we use the method "require" to load external libraries. So naturally such libraries should be called "**requirements**", not "dependencies". I would like to see Shards not make the same nomenclature fail.

"dependencies", on the other hand, is a good name for what gemspec call "requirements" (ugh), and what shard calls "libraries". "libraries" is *okay* since it refers to system libs, even though it is overly general since requirements are libraries too.

**Comment by ysbaddaden** [comment]
No. A shard is a dependency (a project *depends* on a library), from which we require files.

**Comment by trans** [comment]
Well, to be percise, I don't think "depends" means exactly what most people think it means. But then programmer's have never been very good at naming things. 

I simply favor intuitive mnemonic nomenclatures, and always try to imagine what a newbie would think. So personally, as I must "require" files, I do so from "required libraries". Considering what Shards does I suppose the most precise term then would be "requisites", actually.

But considering how summarily this issue was closed...

**Comment by ysbaddaden** [comment]
Sorry if I hurt feelings, but the spec was written years ago, namings follow what other languages and packages managers use.

Changing namings now would 1. break years of compatibility, and 2. confuse users by introducing new terms. Whatever if they happen to fit a little better.

**Comment by straight-shoota** [comment]
There is also a small semantic difference which matters in this context. *dependencies* is a broader term than *requirements*, as not every dependency has to be required. There might also be optional dependencies. Shards currently doesn't support that, but it's not hard to imagine such a feature.
So, *dependencies*  seems to be a better term anyway.

The analogy to `require` is also not 100% solid, because a shard `foo` (installed as a dependency) might not even provide a single file of the same name to require (`require "foo"`) but multiple, optional requireable files (`require "foo/bar"`, `require "foo/baz"`).
