### ISSUE TITLE
Possible recursive symlink in 0.9.0.rc1

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/shards#263]
# Environment

* Crystal 0.27.2
* Shards 0.8.1
* Ubuntu Linux 16.04.5 (WSL)

# Issue

A `lib` entry is generated within every shard that is installed:

```console
$ crystal --version
Crystal 0.27.2 [60760a546] (2019-02-05)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

$ shards --version
Shards 0.8.1 [0147a56] (2019-02-05)

$ git rev-parse HEAD
27815669584b653e0118cf0072c4249fd1c8b461

$ git clean -x -d -f
Removing lib/

$ make
crystal build src/shards.cr -o bin/shards

$ bin/shards --version
Shards 0.9.0.rc1 [2781566] (2019-02-19)

$ bin/shards install
Resolving dependencies
Fetching https://github.com/ysbaddaden/minitest.cr.git
Installing minitest (0.4.2)

$ ls lib
minitest

$ ls lib/minitest/
CHANGELOG.md  lib  LICENSE  Makefile  README.md  shard.yml  src  test  VERSION

$ ls lib/minitest/lib
minitest

$ ls lib/minitest/lib/minitest/
CHANGELOG.md  lib  LICENSE  Makefile  README.md  shard.yml  src  test  VERSION
```

I was not able to find if this was expected or a side effect of recent changes.

This issue is not present in version 0.8.1:

```console
$ crystal --version
Crystal 0.27.2 [60760a546] (2019-02-05)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

$ shards --version
Shards 0.8.1 [0147a56] (2019-02-05)

$ git rev-parse HEAD
27815669584b653e0118cf0072c4249fd1c8b461

$ stat lib
stat: cannot stat 'lib': No such file or directory

$ shards install
Fetching https://github.com/ysbaddaden/minitest.cr.git
Installing minitest (0.4.2)

$ ls lib
minitest

$ ls lib/minitest/
CHANGELOG.md  LICENSE  Makefile  README.md  shard.yml  src  test  VERSION

$ stat lib/minitest/lib
stat: cannot stat 'lib/minitest/lib': No such file or directory
```

Thank you.
❤️ ❤️ ❤️

**Comment by ysbaddaden** [comment]
Yes, this is a2a5e7990ab9a234bea8fbcaea521cc98513607f (transitive dependencies). I merely link the main`lib` folder to each installed shard, so each shard has access to all shards.

We could link only its dependencies, but we must link all reachable dependencies, hence search dependencies recursively, which is more complex than `ln -sf ../../lib .`

Is it a problem?

**Comment by luislavena** [comment]
Thanks for the reference link, for some reason I missed it.

> Is it a problem?

We got some build issues after updating to test this out, but I was not able to reproduce the specific scenario.

Will do a fresh clone of one of our projects and test/compare between 0.8.1 and 0.9.0.

Will send a follow up tomorrow.

Thank you for your promptly response.

Cheers.

**Comment by luislavena** [comment]
Hello!

Apologies for the delay getting back to this, but had to test a few scenarios before confirming that latest 0.9 code works perfectly. What we experienced was a fluke 😅 

Thank you @ysbaddaden for your awesome work as always! ❤️ ❤️ ❤️ 

Cheers.

**Comment by jwoertink** [comment]
I'm getting this. 
![Screen Shot 2019-04-30 at 1 15 03 PM](https://user-images.githubusercontent.com/2391/56990471-0066cd80-6b4a-11e9-96cc-aaed3f475734.png)

I don't think it really affects anything other than being a little weird. This lua shard includes ameba as a development_dependency, but since the `lib` dir symlinks back to itself, there's no ameba available. 

In case it's something you'd like a reproducible example for,

```yml
name: testing
version: 0.0.1
dependencies:
  lua:
    github: jwoertink/lua.cr
    branch: master
```

There's my shard.yml running on `Shards 0.9.0.rc1 [2781566] (2019-04-25)`

**Comment by ysbaddaden** [comment]
This is by design. Development dependencies are never installed for nested dependencies, they're only installed for the the app or library you're working on.

For example a library may use minitest to run its test suite, but thats not required to the library. Once used as a dependency I don't need to resolve and install minitest anymore.

**Comment by jwoertink** [comment]
Yeah, that totally makes sense. I didn't even think about that. Thanks!
