### ISSUE TITLE
Non-blocking dependencies fetching

### ISSUE THREAD

**Issue by j8r** [crystal-lang/shards#371]
Shards fetches each dependency - one at a time. This is a slow process, because each operation blocks the other one. After the dependencies resolution, each download is totally independent of the others.
The speed up gain can be considerable bigger the list is.

On the good side, installing the libraries is fast. Parallelizing it wont be much beneficial, especially since the operations are mainly IO bound (filesystem copy-pasting).

**Comment by waj** [comment]
Absolutely! A few days ago I tried with a dumb implementation of `pmap` and it was really easy to get performance improvements. 

The problem is that not all the dependencies are known before the solver starts working. But at least the explicit deps from the spec file could be downloaded in parallel.

**Comment by j8r** [comment]
Yes, it is possible when the install is done based on the lock file - which is common.
Updating and installing without locks won't be able to benefit fully or not at all, but the parallel fetch for installations based on the lock files is a great start.

**Comment by straight-shoota** [comment]
#539 is a good initiative to resolve this.

However, I think we should figure out some of the higher-level aspects here first.

* The PR restricts to 8 concurrent fetches. What's the explanation for that? Is it just a lucky number? Out of a gut feeling, I wouldn't see a problem with a much higher limit.
* Does the amount need to be configurable at runtime? Could we just pick a good default that works for everyone and call it a day? Unless there's a compelling reason for the command line argument, I'd prefer to leave it out. We can always introduce it later when a use case shows up.

**Comment by m-o-e** [comment]
> The PR restricts to 8 concurrent fetches. What's the explanation for that? Is it just a lucky number?

It defaults to 8 because that was the sweet spot in my local tests
with a few randomly chosen popular shards (I used mainly amber for reference).

Higher parallelism never gained me more than ~2 seconds wallclock.

> Does the amount need to be configurable at runtime?

I think it should be. The current default appears to be a fair middleground
for the general case and a substantial improvement over sequential fetching.

But there may be edge cases where a user wants to lower it (weak internet connection)
or raise it (large number of deps on one level of the tree).

However, wanting to change the parallelism is probably rare, so I guess
it could also be an env-var instead of a CLI argument.

**Comment by straight-shoota** [comment]
I'm wondering what's really the downside of adding *more* concurrent workers? It'd be occupying a few more local resources (memory and file descriptors). But that's hardly a big issue unless you have hundreds of dependencies to fetch.
The limiting factor besides local downlink capacity (and timeout span) is probably how much stress mass usage puts on remote servers, especially considering the likelihood of multiple dependencies being fetched from the same sources.
But those are mostly soft limitations. As long as it's in a reasonable range, I wouldn't expect any immediate failures just because of the number of concurrent requests.
I currently don't see a strong use case for making the number of requests configurable. It probably won't hurt to have an environment variable. Even if it's mostly a dev tool for debugging.

For reference:
* `curl --parallel` uses 50 concurrent requests by default. The limit is configurable and hard limited to 400.
* Modern browsers typically use 6 concurrent request per domain.
* `yarn` uses 8 parallel requests by default. The limit is configurable.

**Comment by m-o-e** [comment]
I don't really have a strong opinion on the default worker count.
(the sweetspot in my local testing was 8)

However, regardless of what default we pick, I would definitely
suggest to leave an escape hatch (cli-arg or env-var) for users
who need to change it. 

It's probably very rarely needed but leaving it out
could easily turn a small annoyance into a big headache.

E.g. when trying to `shards install` on a weak mobile connection
where the parallelism slows it to the point of timeouts.

The last thing I want to do when I find myself in such a situation
is to figure out how to recompile my package manager... ;)
