### ISSUE TITLE
Duplicate keys in spec

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#376]
When shard.yml contains duplicate keys for example two entries called `dependencies`, the spec parser concatenates the values:

```cr
yaml = <<-YAML
name: foo
version: 0.1.0

dependencies:
  foo:
    github: foo/foo
dependencies:
  bar:
    github: bar/bar
YAML
spec = Shards::Spec.from_yaml yaml

spec.dependencies.map(&.name) # => ["foo", "bar"]
```

This is unexpected and differes from any other YAML parser where previous values are simply overriden. For example `YAML.parse` behaves that way:
```cr
YAML.parse(yaml)["dependencies"].as_h.keys # => ["bar"]
```

As a result of this behaviour normalized YAML (for example passing `yaml` through `YAML.parse(yaml).to_yaml` parses differently than the ill-formed spec with duplicate keys.

I'd expect the parser to behave like other YAML parses and only use the last value. That's how it worked before #349. We could also consider to fails parsing such a a spec. Duplicate keys are clearly an error in the shard spec and should be fixed by the author. But issueing a warning is probably better.

**Comment by waj** [comment]
> That's how it worked before #349
Are you sure about that? I can't find yet any change in that PR that might affected this. And I just tried with 0.9.0 and also seems to be merging the values.

Anyway, we should choose what to do because currently the behaviour is undefined. Actually YAML specifies that the keys MUST be unique, so an error would be the strict option. As you said, other YAML parsers just stay with the latest value. That is of course a side effect of doing just nothing when parsing and converting to a dictionary.

I think it should fail to parse. Using the last value is as arbitrary as using the first one or merging. It's very likely an error and assuming any option to install or delete dependencies could lead to undesirable results.

**Comment by bcardiff** [comment]
I agree with the fail to parse policy

**Comment by straight-shoota** [comment]
> Are you sure about that? I can't find yet any change in that PR that might affected this. And I just tried with 0.9.0 and also seems to be merging the values.

Hm, I didn't actually verify that. I just received an error on the shardbox worker that was caused by duplicate dependencies key after updating to shards master. That same shard release never errored before, so something must have changed. But I didn't investigate beyond the current behaviour in shards.
