### ISSUE TITLE
shards build docs

### ISSUE THREAD

**Issue by juozasg** [crystal-lang/shards#431]
Can we add a separate command or a switch for build to run `crystal doc` for dependencies and then create an index.html for the entire project? Would help to have docs in one place. It should be easy to implement.

**Comment by straight-shoota** [comment]
> It should be easy to implement.

Maybe a very crude version would be easy. But it would be far from what you would expect to be properly usable.
This is based on limitations of the doc generator, which honestly needs a serious revamp. We need to work on that first, before discussing how to integrate with shards.
See crystal-lang/crystal#8550 and crystal-lang/crystal#7904 for reference.

I'm closing this issue because at the moment this is not actionable in shards.
