### ISSUE TITLE
shards prune does nothing

### ISSUE THREAD

**Issue by fuzzthink** [crystal-lang/shards#482]
Removed unused dependencies from shard.yml and removed all require in src files. `shard prune` does nothing. The library is still in /lib.

Also, how do I upgrade shards? I'm on  0.11.1 . `shards update shards` doesn't do it.

**Comment by Blacksmoke16** [comment]
I'm pretty sure `shards prune` works based off of your `shard.lock`.  So try doing a `shards update` then `shards prune` after removing the dependency from `shard.yml`.  Otherwise it's still "required".

> Also, how do I upgrade shards?

Normally it gets updated when Crystal get upgraded.  What version of Crystal are you on and how did you install it?

**Comment by straight-shoota** [comment]
Please try again with latest shards release. There's no point in looking at a possible bug in an outdated version that might have been fixed long ago. If you can reproduce with latest (or master), please provide a reproducible example.

Shards binaries are usually distributed with the Crystal release. Some package managers provide a standalone shards package. You can also just download the release tarball for Crystal and extract the shards binary from there. Or build from source in this repository.

**Comment by fuzzthink** [comment]
Updating crystal to the latest updated shards as well and `prune` works now.
